[project]
name = "RbohB-DE"
version = "1.0.0"
dependencies = [
    "pandas",
    "biopython",
    "numpy",
    "matplotlib",
    "seaborn",
    "matplotlib",
    "scikit-learn"
    pydeseq2"
]

[tool.setuptools.packages.find]
where = ["src"]